[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"

Font="Open Sans"
FontSize="13"
# Default is screen height divided by 80 (1080/80=13.5), Options: 0-inf.

RoundCorners="20"

HourFormat="HH:mm"
# Default Locale.ShortFormat.
DateFormat="dddd d MMMM"
# Default Locale.LongFormat.

#################### Profile ####################
ProfileImage="../pfp.png"
ProfileGlowColor="#00f0ff"
#################### Background ####################

Background="background.jpg"
# Must be a relative path.
# Supports: png, jpg, jpeg, gif.
DimBackground="0.75"
# Options: 0.0-1.0.
# Connected with: DimBackgroundColor
CropBackground="true"
# Default false.
# Crop or fit background.
# Connected with: BackgroundHorizontalAlignment and BackgroundVerticalAlignment dosn't work when set to true.
BackgroundHorizontalAlignment="center"
# Default: center, Options: left, center, right.
# Horizontal position of the background picture.
# Connected with: CropBackground must be set to false.
BackgroundVerticalAlignment="center"
# Horizontal position of the background picture.
# Default: center, Options: bottom, center, top.
# Connected with: CropBackground must be set to false.

#################### Colors ####################

TimeTextColor="#ffffff"

BackgroundColor="#21222C"
DimBackgroundColor="#000000"

LoginFieldBackgroundColor="#222222"
PasswordFieldBackgroundColor="#222222"
LoginFieldTextColor="#ffffff"
PasswordFieldTextColor="#ffffff"
UserIconColor="#00f0ff"
PasswordIconColor="#00f0ff"

PlaceholderTextColor="#bbbbbb"
WarningColor="#343746"

LoginButtonTextColor="#ffffff"
LoginButtonBackgroundColor="#343746"
SystemButtonsIconsColor="#F8F8F2"
SessionButtonTextColor="#F8F8F2"

DropdownTextColor="#ffffff"
DropdownSelectedBackgroundColor="#343746"
DropdownBackgroundColor="#21222C"

HighlightTextColor="#bbbbbb"
HighlightBackgroundColor="#343746"
HighlightBorderColor="#343746"

HoverUserIconColor="#00787f"
HoverPasswordIconColor="#00787f"
HoverSystemButtonsIconsColor="#00787f"
HoverSessionButtonTextColor="#00787f"

#################### Form ####################

FullBlur="true"
# Default false.
# If you use FullBlur I recommend setting BlurMax to 64.
BlurMax="24"
# Default 48, Options: 2-64 (can go higher because depends on Blur).

HaveFormBackground="false"
# Form background is transparent if set to false.
# Connected with: BackgroundColor.
FormPosition="center"
# Default: left, Options: left, center, right.

#################### Interface Behavior ####################

HideSystemButtons="false"
HideLoginButton="true"

ForceLastUser="true"
# If set to true last successfully logged in user appeares automatically in the username field.
PasswordFocus="true"
# Automaticaly focuses password field.
HideCompletePassword="true"
# Hides the password while typing.
AllowEmptyPassword="false"
# Enable login for users without a password.
AllowUppercaseLettersInUsernames="false"
# Do not change this! Uppercase letters are generally not allowed in usernames. This option is only for systems that differ from this standard!
BypassSystemButtonsChecks="false"
# Skips checking if sddm can perform shutdown, restart, suspend or hibernate, always displays all system buttons.
RightToLeftLayout="false"
# Revert the layout either because you would like the login to be on the right hand side or SDDM won't respect your language locale for some reason. This will reverse the current position of FormPosition if it is either left or right and in addition position some smaller elements on the right hand side of the form itself (also when FormPosition is set to center).

